[package]
name = "zestalive"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
ecs_common = { workspace = true }
iweird = { workspace = true }
game_resources = { workspace = true }
