[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
codegen-units = 256
debug = 0

[profile.dev.package."*"]
codegen-backend = "llvm"
